# Flutter投资理财App - 代码分析配置
# 此文件配置分析器，用于静态分析Dart代码以检查错误、警告和代码规范
#
# 分析器识别的问题会在支持Dart的IDE中显示
# 也可以通过运行 `flutter analyze` 命令从命令行调用分析器

# 包含Flutter推荐的代码规范
include: package:flutter_lints/flutter.yaml

# 分析器配置
analyzer:
  # 排除不需要分析的目录
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"
  
  # 语言配置
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  # 错误配置
  errors:
    # 将某些警告提升为错误
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    todo: ignore  # 忽略TODO注释

# 代码规范配置
linter:
  rules:
    # 代码风格
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # 导入和库
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    library_prefixes: true
    
    # 命名规范
    camel_case_types: true
    constant_identifier_names: true
    non_constant_identifier_names: true
    library_names: true
    file_names: true
    
    # 代码质量
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true
    
    # Flutter特定规则
    avoid_build_context_in_providers: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_setstate: true
    use_super_parameters: true
    
    # 性能相关
    avoid_function_literals_in_foreach_calls: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_future: true

# 更多信息请参考: https://dart.dev/guides/language/analysis-options
